ropensci/roweb3

- themes/ropensci/layouts/partials/blogs/blog-single.html
I think this is a bug? The columns in bootstrap should add up to 12. 
Related to improving https://github.com/ropensci/roweb3/issues/27
> Make post span page width

- content/blog/2020-09-29-mapscanner/index.Rmd
- content/blog/2020-09-29-mapscanner/index.md
> fix author links

- content/blog/2020-10-06-hacktober2020/index.md
**Questions for Steffi**
- should I add a section on the content of this screenshot? I don't want to essentially copy-paste the whole contrib guide content
- should I include more links in the post or to point more to the contributing guide (e.g. in Make your project collaboration friendly by including a code of conduct...?)
> blog post on (not) Hacktoberfest

- archetypes/Rmd/index.md
- archetypes/md/index.md
- content/blog/2020-09-29-mapscanner/index.md
Clean up the YAML instructions and fix the headings (fixes ropensci-org/blog-guidance#149)
> Fix blog/technote templates

- content/author/julia-gustavsen/_index.md
- content/blog/2020-10-27-editors2020/index.md
Hi @stefaniebutland,
Here is my short bio and a few additional details for my author page. Please let me know if you would like any changes or additional info.
Thanks! Julia
> add JAG bio to blog post and update JAG author page

- content/blog/2020-10-27-editors2020/index.md
Hi @stefaniebutland ,
I have added in the packages that I reviewed and edited. Thanks for digging them up and for the chance to add them in #52.
> Added JAG package reviews to intro editor blog post.

- themes/ropensci/layouts/partials/packages/default-type.html
- themes/ropensci/layouts/partials/packages/package-card.html
In case the registry does not contain information about type.
> add robustness

- themes/ropensci/layouts/partials/whole-page-fragments/review.html
Sorry I didn't see this before to combine with the first :)
> typo fix 2

- content/technotes/2020-11-10-fulltext-story/index.md
- content/technotes/2020-11-17-fulltext-story/index.md
Let me know if you think anything could be changed to the structure, or any details that should be included or not included. Does it make sense? Does anything need to be explained better?
> add draft post on fulltext story of fetching full text

- themes/ropensci/layouts/commcalls/single.html
>  in comm call pages we want the collaborative notes to come before other resources

- content/technotes/2020-12-17-vcr-release/index.md
- content/technotes/2020-12-18-vcr-release/index.md
Hey @steffilazerte - can you take a look at this technote?
> vcr release draft post

- data/resources/statsoftwarereview.json
Thanks to @lcolladotor for spotting this one!
> fix broken link to stat-software-review-book

- themes/ropensci/layouts/blog/list.html
> add button with link to all posts

- .gitignore
- content/blog/2020-11-19-moving-away-travis/index.md
- content/blog/2021-01-29-magick-26/index.md
- content/r-universe/_index.md
- data/resources/runiverse.json
- themes/ropensci/layouts/partials/skeleton/navbar.html
- themes/ropensci/layouts/r-universe/list.html
to add a r-universe page cf #130
> r-universe page

- content/blog/2019-07-15-expanding-software-review.md
- content/blog/2019-12-03-mark-padgham.md
- content/blog/2021-03-09-commcall-stats/index.md
- content/commcalls/2021-03-02/index.md
- data/resources/statsoftwarereview.json
Fix #130 
@mpadge are you happy with these tweaks? For further tweaks e.g. adding your name and featured cards, please ping me now or in the future.
> tweak stat software page

- DESCRIPTION
- data/usecases/usecases.json
- get_use_cases.R
> more use case linking

- netlify.toml
Fix #179 using https://docs.netlify.com/configure-builds/file-based-configuration/ example
> fix netlify.toml

- themes/ropensci/layouts/careers/single.html
- themes/ropensci/layouts/commcalls/single.html
- themes/ropensci/layouts/events/single.html
- themes/ropensci/layouts/partials/blogs/blog-single.html
- themes/ropensci/layouts/partials/email/share-link.html
- themes/ropensci/layouts/partials/email/share-url.html
> Share by email button

- content/events/2021-07-05-useR2021.md
Related to this, should rOpenSci retweet useR! announcement that registrations are now open?
> Add Maëlle's tutorial

- content/commcalls/2021-05-25/index.md
> update comcall description

- content/r-universe/_index.md
> grammar fix? added missing word

- content/blog/2017-04-18-tabulizer/index.md
https://twitter.com/therealfitz/status/776428077123506176
> delete embedded tweet, caused roweb3 deploy fail

- themes/ropensci/layouts/partials/skeleton/navbar.html
> add banner

- themes/ropensci/layouts/partials/skeleton/navbar.html
Fix #218
Requesting a review as you might have an opinion on the order of projects. :slightly_smiling_face:
> move Software Peer Review from About dropdown to Projects

- content/stat-software-review/_index.md
@maelle Can you please confirm that these escape characters are correct? (Change is `<at>` -> `\<at\>`) :+1:
> fix escape characters on stat-software email addresses

- content/blog/2021-06-22-setup-runiverse/index.md
- content/blog/2021-07-13-katex-release/index.md
> Add description to posts to improve the newsletter

- content/blog/2021-08-17-co-working-sessions/index.md
- content/blog/2021-08-17-coworking-sessions/index.md
- content/events/2021-09-07-coworking-2021-09.md
- content/events/2021-10-05-coworking-2021-10.md
- content/events/2021-11-02-coworking-2021-11.md
- content/events/2021-12-07-coworking-2021-12.md
- content/events/2022-01-04-coworking-2022-01.md
- content/events/2022-02-01-coworking-2022-02.md
@stefaniebutland, @njtierney, here is a *very* rough draft. I'm open to any and all suggestions. I'm not sure it's very exciting, so let me know if you have any ideas.
I also created the event for the September coworking session so they could link to each other. @stefaniebutland I left the same label-athon Zoom info, does this need to be updated?
> Announcing social co-working sessions

- data/team/team.json
> add Adam Sparks new editor

- themes/ropensci/static/onboarding/index.html
>  Forward onboading link for reviewers to the form

- archetypes/newsletter/index.md
per Maëlle's request https://github.com/ropensci/biweekly/issues/82#issuecomment-949315818
> add coworking to newsletter template

- themes/ropensci/layouts/partials/skeleton/navbar.html
> Add link to contributing guide to Community Drop-down menu

- data/resources/softwarereview.json
- themes/ropensci/layouts/partials/skeleton/navbar.html
> Easier-to-find links to submission

- content/blog/2018-10-09-jstor.md
- content/blog/2019-02-27-handlr-release.Rmd
- content/blog/2019-02-27-handlr-release.md
- handlr post citation -> citations in Rmd
> consistent use of  citations tag

- content/author/emily-riederer/_index.md
- content/blog/2021-11-18-devguide-0.7.0/index.md
> dev guide release post, 0.7.0

- archetypes/newsletter/index.md
- data/usecases/usecases.json
Fix #299
Fix https://github.com/ropensci/biweekly/issues/89
> update archetype & use cases

- content/author/jeroen-ooms/_index.md
- themes/ropensci/layouts/author/list.html
Fix #16
- Uses the runiv YAML field if set (will need to be documented in the blog guide)
- Falls back on the GitHub username
> Add r-universe link to author pages

- netlify.toml
Via https://answers.netlify.com/t/access-control-allow-origin-policy/1813/2 & https://developer.mozilla.org/en/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
> Change Access-Control for fonts

- content/blog/2022-01-31-a-blend-of-package-build-failuresindex.md
- content/blog/2022-02-04-a-blend-of-package-build-failures/index.md
> Package build failures

- content/careers/2022-02-02-community-manager.md
- themes/ropensci/layouts/careers/single.html
Initial draft post just to test embedding form directly on page. Looks good in local preview.
> Community manager job ad

- themes/ropensci/layouts/help-wanted/list.html
> Fix 'Help Wanted' page dates

- content/events/2022-06-07-epiverse.md
- content/events/2022-06-10-wids-la-plata.md
> add current talks

- content/blog/2022-06-21-introducing-yanina-es/index.md
- content/blog/2022-06-21-introducing-yanina/index.md
When we are ok with this I will translate to Spanish and create that other blog post.
> Draft blog post introducing Yani :-)

- content/blog/2022-07-01-evaluating-github-activity-for-contributors/index.md
- content/blog/2022-07-12-evaluating-github-activity-for-contributors/index.md
I think `roblog::ro_lint_md()` complaints are false positives.
> Evaluating GitHub Activity for Contributors

- content/blog/2022-07-11-coc-update/index.md
- content/blog/2022-07-12-coc-update/index.md
- Do we also need to mention the changes on the CoC Committee?
> CoC update blog post

- themes/ropensci/layouts/_default/featured-card.html
- themes/ropensci/layouts/_default/post-complete-summary.html
- themes/ropensci/layouts/_default/post-summary.html
- themes/ropensci/layouts/author/terms.html
- themes/ropensci/layouts/commcalls/single.html
- themes/ropensci/layouts/partials/blogs/blog-single.html
- themes/ropensci/layouts/tags/list.html
- themes/ropensci/layouts/talks/list.html
> fix typography of blog titles

- content/events/2022-09-06-coworking-2022-09.md
September draft, hopefully October soon.
> Coworking Events

- content/events/2022-11-01-coworking-2022-11.md
- content/events/2022-12-06-coworking-2022-12.md
@yabellini could you have a look at the November event to make sure I've represented it as I should? Ideally we'll have the Champions Website up soon and I'll add links to this site.
> Add November and December coworking events.

- content/packages/stat.md
> add stat category

- themes/ropensci/layouts/partials/packages/package-card.html
> Put docs first

- content/blog/2022-09-13-contributing/index.md
- content/blog/2022-10-20-call-for-mentors-champions-program/index.md
- content/champions/files/mentors_champions_template.md
Blog post for Call for Mentors.  Was reviewed by Camille and Lou.
The idea is to publish today or tomorrow, so we can include in the newsletter.
> Call for mentors

- content/author/pao-corrales/_index.md
I'm not sure how the profile picture works... but I've followed the instructions :see_no_evil:
> add author profile

- content/author/maëlle-salmon/_index.md
- content/author/yanina-bellini-saibene/_index.md
- themes/ropensci/layouts/author/list.html
> add mastodon to author profiles

- content/champions/_index.md
> Updating info about the champions program

- content/author/mark-padgham/_index.md
- data/team/team.json
> rm mpadge twitter links

- content/commcalls/2022-10-24/index.md
Adding link to video and google doc with notes.
- We need to check why the audio looks not in sync with the image on the video.
> Adding video and google doc

- content/blog/2022-11-29-multilingual-publishing-en/index.md
I reviewed the post and also enrolled chatGPT as an experiment. I prompted it with "This is the introduction for a blog post. Can you tweak it to correct any grammar mistakes but maintaining the style, voice and register?" (I worked section by section). I think it worked pretty well, since with no changes to content or ordering it tweaked all those little details that are hard to nail for us non-native speakers (like prepositions, infinitive vs. gerund, word ordering, false friends, usw).
> Miltilingual post: Revision by Elio and chatGPT

- themes/ropensci/layouts/partials/skeleton/footer.html
> Change mastodon link to new account

- content/blog/2021-03-04-r-universe-buildsystem/index.md
- content/blog/2021-04-09-r-universe-articles/index.md
- content/blog/2021-06-22-setup-runiverse/index.md
- content/blog/2021-09-03-runiverse-docs/index.md
- content/blog/2021-10-14-runiverse-badges/index.md
- content/blog/2021-11-24-runiverse-rss/index.md
- content/blog/2022-01-06-runiverse-renv/index.md
- content/blog/2022-03-23-runiverse-search/index.md
- content/blog/2022-11-29-postdoc-docs/index.md
- content/blog/2023-01-30-runiverse-permanent-urls/index.md
- content/blog/2023-02-07-runiverse-registry-repo/index.md
- themes/ropensci/layouts/partials/blogs/blog-single.html
Not all posts tagged R-universe are post of yours.
Should the logic also include a condition on the author?
> Add r-universe intro to all posts tagged R-universe

- content/blog/2023-03-17-ropensci-news-digest-march-2023/index.Rmd
- data/resources/champions.json
@maelle I also added an extra sentence to your bit about `pkg_name_check()` - let me know if that's okay :smile:  Happy to remove if you'd prefer that not to be there?
> News 2023 03

- content/blog/2023-03-31-cran-to-git/index.md
- content/blog/2023-04-03-cran-to-git/index.md
Trying to roughly explain how we automatically ingest packages.
> Technote about cranscraper

- content/author/mike-mahoney/_index.md
- content/blog/2023-04-04-waywiser-is-now-a-part-of-ropensci/index.md
Add post by @mikemahoney218 :pray: (I only added a link to tidymodels, to the software review page of the website, and reformatted footnotes)
> add waywiser tech note

- content/blog/2023-04-13-champions-program-teams/index.md
I've changed from a third-person perspective to a first-person, made a few edits to the flow and added why I'm interested in being a part of this.
> Update Adam Sparks - Mentor section

- themes/ropensci/i18n/fr.toml
- themes/ropensci/layouts/partials/blogs/blog-single.html
- themes/ropensci/layouts/partials/blogs/comments.html
> tweaks R-universe posts

- config.toml
- netlify.toml
- themes/ropensci/layouts/author/list.html
> fix: make r-universe link conditional

- content/author/beatriz-milz/_index.md
- content/author/haydee-svab/_index.md
Hi @yabellini !
I created a file for me and Haydee to add our author information.
@hsvab is there anything you would like to change? 
From: https://github.com/ropensci/roweb3/pull/552#issuecomment-1536691483
> Create author profile for Beatriz Milz and Haydee Svab [CHAMPIONS PROGRAM]

- content/blog/2023-04-11-troubleshooting-pandoc-problems-as-an-r-user/index.Rmd
This is just a way to add to #531 as I don't have access to push the current PR branch. 
It probably makes it easier for you @maelle to amend any of those changes and suggestion. 
Feel free to rephrase, amend, remove as you see fit! 
After that I believe #531 is ready - sorry for the delay !
> Contritbution to Tech note about pandoc troubleshooting 

- themes/ropensci/layouts/talks/list.html
> fix: sort talks better

- content/blog/2021-02-16-package-citation/index.md
> update old blog post on package citations

- config.toml
- themes/ropensci/layouts/blog/list.json.json
- themes/ropensci/layouts/partials/blogs/author-img.html
Fix #630 
https://deploy-preview-631--ropensci.netlify.app/blog/index.json
> Tweak the blog JSON feed for Rogue Scholar ingestion

- content/author/jonathan-keane/_index.md
> add missing author file

- themes/ropensci/layouts/blog/list.json.json
@mfenner thanks for catching this!
> fix: fix favicon and feed_url links in JSON feed

- themes/ropensci/i18n/en.toml
- themes/ropensci/i18n/es.toml
- themes/ropensci/i18n/fr.toml
- themes/ropensci/layouts/partials/blogs/blog-single.html
- themes/ropensci/layouts/partials/blogs/doi.html
- themes/ropensci/layouts/partials/skeleton/footer.html
- themes/ropensci/layouts/partials/skeleton/head.html
- themes/ropensci/static/copypaste.css
- themes/ropensci/static/scripts/copypaste.js
https://deploy-preview-632--ropensci.netlify.app/blog/2023/08/25/news-august-2023/
> Samples of DOI inclusion

- content/author/jon-harmon/_index.md
- content/events/2024-01-09-coworking-2024-01.md
- content/events/2024-02-06-coworking-2024-02.md
Coworking events for January and February
> Add coworking Jan/Feb

- config.toml
- netlify.toml
> refactor: update Hugo version

- themes/ropensci/layouts/partials/skeleton/footer.html
- themes/ropensci/layouts/partials/skeleton/head.html
- themes/ropensci/static/scripts/matomo.js
I hope this one is less annoying.
> Use another cookie consent widget

- archetypes/newsletter/index.md
- content/blog/2023-11-24-news-november-2023/index.Rmd
- content/blog/2023-11-24-news-november-2023/index.md
- data/usecases/usecases.json
@steffilazerte Beside the usual human-generated content I added a new sentence at the bottom, about donations.
> November news

- content/events/2023-10-18-champion-program-latinR.md
- content/events/2023-10-19-rOpenSci-latinR.md
- content/events/2023-11-17-r-bcn.md
> Adding last talk of the year 

- data/resources/multilingual.json
- data/team/translators.json
- themes/ropensci/layouts/partials/resources/resources-cards.html
> edits to the multilingual project page

- content/blog/2024-02-19-waywiser-call-help/index.md
- content/blog/2024-02-22-waywiser-call-help/index.md
@mikemahoney218 here's the PR to review!
The publication date is flexible.
> waywiser call for contributions

- content/blog/2024-02-23-ropensci-news-digest-february-2024/index.Rmd
- content/blog/2024-02-23-ropensci-news-digest-february-2024/index.md
> February news

- content/author/tony-fischetti/_index.md
- content/blog/2024-02-22-call-help-assertr/index.md
- content/blog/2024-02-27-call-help-assertr/index.md
@tonyfischetti Here's the PR to review, see in particular my TODO notes.
The publication date is flexible.
> assertr call for contributions

- content/author/joseph-obrien/_index.md
- content/blog/2024-02-22-qualtrics-call-help/index.md
- content/blog/2024-03-01-qualtrics-call-help/index.md
For your review @juliasilge @jmobrien :pray:
> qualtRics call for contributions

- content/blog/2024-03-11-devguide-release-0.9.0/index.es.md
- content/blog/2024-03-11-devguide-release-0.9.0/index.md
> Dev guide release post

- content/author/beatriz-milz/_index.es.md
- content/author/carolina-pradier/_index.es.md
- content/author/cesar-luis-aybar-camacho/_index.es.md
- content/author/haydee-svab/_index.es.md
- content/author/mauro-lepore/_index.es.md
> add missing Spanish author files

- content/events/2023-12-21-Portuguese-translation.md
- content/events/2024-06-04-SER.md
- content/events/2024-06-11-CZI.md
- content/events/2024-07-10-useR.md
Add 3future  events with rOpenSci participation.
> Yani at SER - Brazil

- content/blog/2020-10-27-editors2020/index.md
* I still work for the same organization but it change its name.
* I don't use twitter much and instead I use LinkedIn a lot.
> Change the name of my employer and link to social media

- content/events/2024-08-06-coworking-2024-08.md
> Coworking 2024-08 - Add notes

- content/r-universe/_index.md
- data/resources/runiverse.json
- themes/ropensci/layouts/r-universe/list.html
> streamline R-universe project page

- themes/ropensci/layouts/r-universe/list.html
> add temporary alert about community call

- config.toml
- content/blog/2017-10-31-ozunconf2017.md
- content/blog/2017-11-21-ochRe.md
- content/blog/2020-07-15-subtitles/index.md
- content/blog/2021-06-08-world-ocean-day/index.md
- content/blog/2022-02-15-gghdr/index.md
- netlify.toml
- themes/ropensci/layouts/author/list.html
- themes/ropensci/layouts/citations/list.html
- themes/ropensci/layouts/help-wanted/list.html
- themes/ropensci/layouts/packages/single.html
- themes/ropensci/layouts/packages/single.json.json
- themes/ropensci/layouts/partials/blogs/doi.html
- themes/ropensci/layouts/search/list.json.json
> update Hugo to latest version

- content/author/alican-cagri-gokcek/_index.md
> Remove superfluous slash

- content/blog/2024-08-19-news-august-24/index.Rmd
- content/blog/2024-08-19-news-august-24/index.md
@maelle This includes merging of current main with your PR #823, but directly only changes `index.Rmd`. I suggest you first sync your PR with current main, then I'll sync this and reduce the "23 files changes" to one.
> pkgstats daily updates

- config.toml
- content/blog/2023-12-05-divide-y-venceras-de-polar-al-polarverse/index.en.md
- content/blog/2023-12-05-divide-y-venceras-de-polar-al-polarverse/index.es.md
- content/blog/2023-12-05-divide-y-venceras-de-polar-al-polarverse/index.pt.md
The blog post was cross-posted with LatinR (as we talked), and @beatrizmilz translated to Portuguese.  I'm adding that version here to our web blog. 
I also added the editor YAML field: Steffi for English, Yani for Spanish and Bea for Portuguese.
> Polarverse blog post translated to Portuguese

- content/blog/2016-03-28-software-review.md
markdownlinks must be on 1 line to work.
> fix link in 2016-03-28-software-review.md

- content/events/2024-11-05-coworking-2024-11.md
Adding the November 2024 coworking event. 
@stefaniebutland when the preview is live could you take a quick look and make sure you're happy with the way I've describe both you and the event in general? Feel free to drop any comments/changes you'd like here as a comment or make them directly to the PR.
> Nov 2024 coworking event

- content/events/2024-12-03-coworking-2024-12.md
> Add December 2024 coworking event

- content/blog/2022-11-23-r-universe-stars-1/index.md
I add Pablo and me as authors so the r-universe stars post can be index in; 
https://ropensci.org/author/pablo-tiscornia/
https://ropensci.org/author/juan-pablo-ruiz-nicolini/
> add authors in index.md

- content/author/mark-padgham/_index.md
- data/team/team.json
> add @mpadge bluesky

- content/author/jeffrey-stevens/_index.md
Add Mastodon and Bluesky, fix homepage
> Update Jeffrey Stevens author info

- content/blog/2018-07-26-educollab-community.md
- content/blog/2018-12-14-pdftools-20.md
- content/blog/2018-12-20-spelling-20.md
- content/blog/2019-01-09-hugo.md
- content/blog/2019-01-10-vitae/index.md
- content/blog/2019-05-21-rodev.md
- content/blog/2019-08-15-news-aug2019.md
- content/blog/2019-09-27-imaging-stack.md
- content/blog/2019-12-19-urls-checking/index.md
- content/blog/2020-04-14-devguide-release/index.md
- content/blog/2020-05-07-rmd-citations/index.md
- content/blog/2020-10-22-devguide-0-5-0/index.md
- content/blog/2021-11-23-cffr/index.Rmd
- content/blog/2021-11-23-cffr/index.md
- content/blog/2021-11-24-runiverse-rss/index.md
- content/blog/2022-05-20-ropensci-news-digest-may-2022/index.Rmd
- content/blog/2022-05-20-ropensci-news-digest-may-2022/index.md
- content/blog/2022-06-16-why-bother-writing-an-api-client/index.Rmd
- content/blog/2022-10-21-ropensci-news-digest-october-2022/index.Rmd
- content/blog/2022-10-21-ropensci-news-digest-october-2022/index.md
- content/blog/2023-01-13-curl5-release/index.md
These are the last blog post that have twitter messages.
Close  #905
> Removing twitter

- content/events/2025-01-14-coworking-2025-01.md
Merge just before coworking Tuesday Jan 14th
> Add notes to coworking event

- content/blog/2024-12-03-r-universe-r-consortium-tlp/index.md
To follow Steffi's feedback in the newsletter content
> Tweak title

- content/blog/2017-09-01-nsf-softwarereview/index.es.md
- content/blog/2021-07-27-censo2017/index.es.md
- content/blog/2022-04-19-software-review-editorial-challenges/index.es.md
- content/blog/2022-10-19-censo2017-one-year-after/index.es.md
- content/blog/2023-01-12-multilingual-publishing/index.es.md
- content/blog/2023-02-21-champions-kick-off/index.es.md
- content/blog/2023-02-27-runiverse-discovering/index.es.md
- content/blog/2023-03-30-r-universe-stars-3/index.es.md
- content/blog/2023-06-06-r-universe-stars-4/index.es.md
- content/blog/2023-06-09-communication/index.es.md
- content/blog/2023-09-15-r-universe-stars-5/index.es.md
- content/blog/2023-11-06-r-universe-interviews/index.es.md
- content/blog/2024-03-11-devguide-release-0.9.0/index.es.md
- content/blog/2024-07-09-multilingual-documentation-in-r/index.es.md
- content/blog/2024-10-10-czi-latam-grant/index.es.md
- content/blog/2024-12-03-r-universe-r-consortium-tlp/index.es.md
- content/blog/2024-12-17-localization-guide/index.es.md
- content/commcalls/2023-11-23/index.es.md
- content/technotes/_index.es.md
- data/team/champions.json
- data/team/mentors.json
- themes/ropensci/layouts/technotes/list.html
> Fixes on Spanish pages

- themes/ropensci/layouts/partials/blogs/blog-single.html
- themes/ropensci/layouts/partials/blogs/doi.html
- themes/ropensci/layouts/partials/skeleton/head.html
Fix #872
@mfenner when exactly will you pull the plug on the current production API?
> start work on new Rogue Scholar API

- themes/ropensci/layouts/partials/blogs/blog-single.html
- themes/ropensci/layouts/partials/blogs/doi.html
- themes/ropensci/layouts/partials/skeleton/head.html
> use DOI from params in templates

- data/team/team.json
- themes/ropensci/i18n/en.toml
- themes/ropensci/i18n/es.toml
- themes/ropensci/layouts/partials/translate.html
> make change of software review leadership official

- content/events/2025-04-01-coworking-2025-04.md
- themes/ropensci/layouts/events/single.html
- themes/ropensci/layouts/partials/calendar/calendar.html
Fix #822
Unfortunately it's a bit long. Example to be removed before merging.
> show end date

- content/events/2025-05-06-coworking-2025-05.md
- content/events/2025-06-03-coworking-2025-06.md
Coworking events for May and June
> June coworking and May placeholder

- content/author/haydée-svab/_index.es.md
- content/author/haydée-svab/_index.md
- content/blog/2023-05-09-champions-program-teams/index.md
- content/blog/2023-05-19-ropensci-news-digest-may-2023/index.md
- content/blog/2024-01-09-latinamerica-champion-program/index.es.md
- content/blog/2024-01-25-january-news/index.md
- content/blog/2024-03-20-champions-program-projects/index.md
- content/blog/2025-03-24-numfocus-unconf/index.md
- content/blog/2025-03-27-news-march-2025/index.Rmd
- content/blog/2025-03-27-news-march-2025/index.md
- content/blog/2025-04-03-conversacion-programa-camp/index.es.md
- content/events/2024-11-20-LatinR.md
- data/team/champions.json
@yabellini for info in older entries Haydée's name was written Haydee.
> fix Haydée's name

- content/how-to-cite-ropensci.md
Fix #939
@jeroen what to use for R-universe?
@yabellini do we also need something for the champions program and multilingual publishing? if so what?
@mpadge does the citation for stat peer-review look ok?
> start updating how to cite

- content/events/2025-05-06-datasci-careers-feds.md
Draft post for event. Date and main participants still need confirmation.
@stefaniebutland @jules32
> Event: Career Paths for U.S. Federal Data Scientists

- content/events/2025-05-06-coworking-2025-05.md
- content/events/2025-05-06-datasci-careers-feds.md
- content/events/2025-05-13-RUG-Salt-Lake-2025.md
- content/events/2025-05-19-Rencontres-2025.md
- content/events/2025-06-13-StateOfR-2025.md
- netlify.toml
- themes/ropensci/layouts/events/single.html
- themes/ropensci/layouts/partials/calendar/calendar.html
@noamross With https://gohugo.io/functions/time/in/ I have to use IANA codes, so it doesn't look as good as saying EDT I guess?
> start adding tz to event

- themes/ropensci/layouts/partials/whole-page-fragments/community.es.html
> review spanish

- content/r-universe/_index.es.md
- content/r-universe/_index.md
Fix #1052
This is the text from https://docs.r-universe.dev/infra/governance.html#funding
If you are happy with it @jeroen we'll still need a review of the Spanish translation by @yabellini before merging.
> add funding info for R-universe

- content/blog/2025-06-12-editors2025/index.md
Add detail about Emi for 2025 editor blog post
> Add detail to 2025 editor blog post

- content/author/monika-avila-marquez/_index.md
Added author Monika Avila Marquez to content/author
> added_author_monikaavila

- content/events/2025-10-07-coworking-2025-10.md
@maelle, what do you think? Should we elaborate more on the blog post? How do you feel about the way I've described you? Feel free to make changes!
> Add @maelle and note blog post

- content/events/2025-11-04-coworking-2025-11.md
Draft of the event page for the November coworking event
> Coworking 2025-11
