archetypes/Rmd/index.md, archetypes/md/index.md
Just a minor change overlooked when moving from roweb2 to roweb3.
This PR changes the mentions of roweb2 to roweb3 on the archtypes templates of the blog.
=> Change mention of roweb2 to roweb3 on archtypes

content/author/mauro-lepore/_index.md
Relates to #52
I added my orcid and img url based on @maelle's author page:
https://raw.githubusercontent.com/ropensci/roweb3/master/content/author/ma%C3%ABlle-salmon/_index.md
This change reponds to this request by @stefaniebutland:
> Check your rOpenSci author page and request any changes (by
> reply to this email or by pull request).
--
I submit directly following what I see at https://github.com/ropensci/roweb3/pull/52, but let me know if you prefer me to close and resubmit from my fork.
=> Add 'orcid' and 'img' to maurolepore's page

themes/ropensci/layouts/commcalls/single.ics, themes/ropensci/layouts/events/single.ics
add mailto:no-reply@ropensci.org to replace mailto:info@ropensci.org so we don't get email when someone adds community call to their calendar
=> Stef noreply

archetypes/Rmd/index.md, archetypes/md/index.md, content/blog/2020-09-29-mapscanner/index.md, themes/ropensci/layouts/partials/skeleton/head.html
Fix #8 
Cf https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image
@ropensci/blog-editors if you approve this I'll also make a PR in the blog guide.
=> Add twitter:image:alt in Twitter cards

content/blog/2021-02-23-devguide-0.6.0/index.Rmd, content/blog/2021-02-23-devguide-0.6.0/index.md
Trying something new: for review the links are to the dev dev guide, I'll switch to production dev guide links after the release of said dev guide!
=> dev guide 0.6.0

content/blog/2021-09-03-runiverse-docs/index.md
Fixes a link in the [rOpenSci docs are now built on r-universe](https://ropensci.org/blog/2021/09/03/runiverse-docs/) article.
=> fix link to "precompute-vignette" article

content/blog/2020-10-27-editors2020/index.md
use tags `editors` and `rOpenSci team`. previously tags were used inconsistently
=> add tags to editors posts

themes/ropensci/layouts/partials/calendar/events.html
Fix #263
I moved the instructions to below the events so it is less a problem to make them longer. Does this work?
=> more calendar instructions

themes/ropensci/layouts/commcalls/single.ics, themes/ropensci/layouts/events/list.ics, themes/ropensci/layouts/events/single.ics
Fix #288 (excellent point, it's true that the current setup assumed a few more clicks to get the Zoom URL via the event description!).
@stefaniebutland it works for me but I'd be grateful for a review.
Ideally test it on two events 
- one with a zoom URL (co-working)
- one without it (Jeroen's NHS-R talk)
And on one comm call.
I am a bit worried the ics files might have info truncated depended on where they're added. Do we know what software Dan Katz used for their calendar?
=> add Zoom URL to events ICS

content/events/2022-01-04-coworking-2022-01.md, content/events/2022-02-01-coworking-2022-02.md, content/events/2022-03-01-coworking-2022-03.md, content/events/2022-04-05-coworking-2022-04.md, content/events/2022-05-03-coworking-2022-05.md, content/events/2022-06-07-coworking-2022-06.md
Added the coworking events for March, April, May and June.
Stef, I've got you as a reviewer for a sanity check of the dates and timezones! I've included a hidden bit of R code to give me a hand in double checking the dates (with timezone changes etc.) and maybe next time I'll write out a script for creating the event entirely (we'll see, it's not really that time consuming!).
=> Add coworking events until June 2022

content/author/joel-nitta/_index.md, content/blog/2022-09-23-ropensci-news-digest-september-2022/index.Rmd
@joelnitta This is the announcment of your package and our new badges. ~~It includes an "author" file for you. I can't assign you as a reviewer here, but please add any additional information you like to your author file. Have a look at others for typical fields, which commonly include a one-line bio, and an ORCID id, and add any of those if you want. The author files link directly to internal pages, like [my one here](https://ropensci.org/author/mark-padgham/). Yours will be an initial placeholder, but with external links to the fields in your author file.~~
Update: Sorry Joel, author files only get started when you have your first internal page on the main website, such as a blog post. Link updated to your personal website instead.
=> new stats badges

themes/ropensci/layouts/partials/whole-page-fragments/volunteer.html
@yabellini commented that with the current attribution position inside the alternative text, a screenreader would read the info 10 times.
@karthik do you think that looks ok? is it ok reg the contract?
=> Change attribution position

themes/ropensci/layouts/author/list.html, themes/ropensci/layouts/partials/whole-page-fragments/team/team-member.html
Including the `rel="me"` attribute in mastodon links allows RO team members to use the `about/` page or their author page as verification links in Mastodon, verifying that they are the RO team members they claim.
=> add rel="me" to mastodon links

content/blog/2022-11-23-r-universe-stars-1-en/index.md, content/blog/2022-11-23-r-universe-stars-1-es/index.md
- fixed a typo
- used the preface YAML parameter (I had forgotten about it myself)
- used the Vimeo shortcode after making the video public on Vimeo. 
I noticed that in the deployed version of the website there was no sidebar, so one of the HTML added in the Markdown had broken something. Now things look ok.
=> typo + no HTML

content/blog/2023-02-28-r-universe-stars-2-fr/index.md
Hey there 👋 
I've noticed an error when following the link in the French version of the blog post of the interview of Sébastien Rochette. I've checked with the other languages and they seem fine. So probably an 'https' that was cut as somepoint in the writing/translating process.
=> Fix link to Bakacode in FR version of blogpost

archetypes/Rmd/index.md, archetypes/md/index.md, archetypes/newsletter/index.md, content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd, content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.md, content/blog/2022-08-09-working-with-qualtrics-data-excluding/index.md, content/blog/2022-12-06-save-ggplot2-targets/index.md, themes/ropensci/layouts/careers/single.html, themes/ropensci/layouts/commcalls/single.html, themes/ropensci/layouts/events/single.html, themes/ropensci/layouts/partials/blogs/blog-single.html, themes/ropensci/layouts/partials/mastodon/share-url.html, themes/ropensci/layouts/partials/skeleton/footer.html, themes/ropensci/layouts/partials/skeleton/head.html, themes/ropensci/layouts/partials/twitter/share-link.html, themes/ropensci/layouts/partials/twitter/share-url.html
Fix #590
- Remove link to Twitter account from the footer. (is this the right choice?)
- Remove button to share on Twitter from the sidebar of posts, job postings, comm calls. (is this the right choice?)
- New posts will use the "social" metadata, for old ones the templates will still pick up the "twitter" metadata. I have checked the preview on Twitter/Mastodon and Slack for the Qualtrics & cite packages post I edited but would appreciate a second pair of eyes. https://deploy-preview-592--ropensci.netlify.app/blog/2022/08/09/working-with-qualtrics-data-excluding/ + https://deploy-preview-592--ropensci.netlify.app/blog/2021/11/16/how-to-cite-r-and-r-packages/
=> less twitter

content/blog/2024-02-23-ropensci-news-digest-february-2024/index.Rmd, content/blog/2024-02-23-ropensci-news-digest-february-2024/index.md
The link to the podcast referred to the podcast homepage, not a specific episode. It took me a whole episode (the latest one) to realize I was listening to the wrong one. 😅 It will get even harder in the future, when the episode moves down on the page. The new link refers to a timestamp in the correct episode.
Also corrected a typo.
=> Update link to podcast

content/blog/2024-03-29-from-the-founding-director-my-farewell-to-ropensci/index.md
I clicked on the link at the bottom of the post to realize there was a tiny typo in the year of the link 😉
=> Correct typo in link to other post

content/blog/2024-04-12-gsod-announcement/index.md, themes/ropensci/layouts/partials/blogs/blog-single.html
=> Announce R-U GSoD, stop using preamble for R-U posts (#752, #754))

content/blog/2024-01-16-deepl-update-babeldown/index.md, content/blog/2024-02-15-intro-champions-2024/index.md, content/blog/2024-02-22-stylish-code/index.md, content/blog/2024-03-07-package-marketing/index.md, content/blog/2024-03-11-devguide-release-0.9.0/index.es.md, content/blog/2024-03-18-package-testing-principles/index.md, content/blog/2024-03-20-champions-program-projects/index.md, content/blog/2024-04-12-gsod-announcement/index.md, content/blog/2024-04-18-fostering-equity-and-leadership/index.en.md, content/blog/2024-05-17-communication-tips-oss-project/index.Rmd, content/blog/2024-05-17-communication-tips-oss-project/index.md, themes/ropensci/i18n/en.toml, themes/ropensci/i18n/es.toml, themes/ropensci/i18n/fr.toml, themes/ropensci/layouts/partials/blogs/blog-single.html
Examples:
- https://deploy-preview-765--ropensci.netlify.app/blog/2024/05/17/communication-tips-oss-project/
- https://deploy-preview-765--ropensci.netlify.app/blog/2024/03/07/package-marketing/
Questions
- Does it look good?
- How do we backfill the editor field of older posts?
- Should we later consider adding a list of posts edited by a person, on that person's author page?
- This won't appear on R Bloggers and Rogue Scholar as far as I know. I could ask Rogue Scholar what the field for editors could be.
=> work on acknowledging post editors

content/blog/2024-04-16-markdown-programmatic/hw-template.md, content/blog/2024-04-16-markdown-programmatic/index.Rmd, content/blog/2024-04-16-markdown-programmatic/index.md
I've added some more context for this along with some structure for the packages (separating out parsermd into a different section). I will leave my review on #751.
=> Structure packages and add more context

content/blog/2023-12-05-divide-y-venceras-de-polar-al-polarverse/index.en.md, content/blog/2023-12-05-divide-y-venceras-de-polar-al-polarverse/index.es.md
LatinR domain used to be latin-r.com, but recently changed to latinr.org
The conference is cited in the blogpost from JP Ruiz Nicolini, and the link is broken.
This PR fixes the links for the conference in that blogpost!
@yabellini
=> Update LatinR domain

content/events/2020-07-09-user.md, content/events/2021-07-05-useR2021.md, content/events/2023-03-01-mentor-orientation.md, content/events/2023-04-04-how-ropensci-review.md, content/events/2023-05-18-how-to-contribute-base-r.md, content/events/2023-05-19-developing-software-together.md, content/events/2024-02-15-mentor-orientation.md, content/events/2024-02-15-stylish-code.md, content/events/2024-03-01-pkg-dev-mechanics-champions.md, content/events/2024-04-01-pkg-dev-not-rocket-science-champions.md, content/events/2024-04-03-Champions.md, content/events/2024-04-17-how-ropensci-review.md, content/events/2024-06-04-SER.md, content/events/2024-07-23-developing-software-together.md, content/talks-papers/_index.md, content/training/_index.md, data/resources/resources.json, themes/ropensci/layouts/partials/resources/talk-card.html, themes/ropensci/layouts/partials/skeleton/navbar.html, themes/ropensci/layouts/partials/talks/talk-table.html, themes/ropensci/layouts/talks-papers/list.html, themes/ropensci/layouts/talks/list.html, themes/ropensci/layouts/training/list.html
Fix #844
We'd need to do some backfilling so that things will look better.
Contrary to other events where we create the event Markdown file in advance, here we can't do that as most training sessions are not public.
=> Work towards a training page with past material

themes/ropensci/layouts/r-universe/list.html
It removes it from the source, it already no longer appears on the website thanks to the template logic.
=> Remove R-universe comm call alert

themes/ropensci/layouts/blog/list.json.json
Part of #970
@mfenner is this what you mean? The id here is the DOI string, like "10.59350/8vw43-jy784": should it be the full URL at doi dot org instead?
=> use DOI in RSS feed

content/commcalls/2025-09-29/index.md, content/events/2025-09-09-coworking-2025-09.md, content/events/2025-10-07-coworking-2025-10.md, themes/ropensci/i18n/en.toml, themes/ropensci/i18n/es.toml, themes/ropensci/layouts/_default/featured-card.html, themes/ropensci/layouts/events/list.html, themes/ropensci/layouts/events/single.html
Fix #1116 
The solution is to use what we use for featured blog posts.
The downside of _rendering_ the featured events is that the card uses the _language of the event_ not the language of the page from which it is rendered. However this was already a problem, and this PR fixes the look of the card not the way it is rendered.
=> improve featured event design
